version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5400:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
